root: true
extends:
  - eslint:recommended
  - plugin:n/recommended
  - google
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - plugin:astro/recommended
plugins:
  - import
  - prettier
env:
  browser: true
  node: true
  es6: true
  es2017: true
  es2020: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2022
  sourceType: module
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.json
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - '*.astro'
rules:
  n/no-missing-import: off
